---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: java-pipelines-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: (event == "pull_request" && target_branch == "main" && ( !has(body.pull_request) || !body.pull_request.draft) ) || (event == "push" && target_branch.startsWith("gh-readonly-queue/main/") && body.head_commit != "null" )
    pipelinesascode.tekton.dev/task: "[task/git-clone/0.1/git-clone.yaml, .tekton/tasks/task-lint.yaml, .tekton/tasks/ec-checks.yaml, .tekton/tasks/task-switchboard.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image-target
      value: quay.io/konflux-ci/appstudio-utils:latest
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: workspace
    tasks:
      - name: clone-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: workspace
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
          - name: depth
            value: "0"

      - name: task-switchboard
        taskRef:
          name: task-switchboard
        params:
          - name: revision
            value: "$(params.revision)"
          - name: utils_image
            value: "$(params.image-target)"
          - name: expressions
            value:
              - tasks := strings.any_prefix_match(input, ["task/", "external-task/", "hack/", ".tekton/"])
              - tasks_pipelines := strings.any_prefix_match(input, ["task/", "external-task/", "pipelines/", "hack/", ".tekton/"])
        runAfter:
          - clone-repository
        workspaces:
          - name: source
            workspace: workspace

      - name: task-lint
        when:
          - input: "tasks"
            operator: "in"
            values: ["$(tasks.task-switchboard.results.bindings[*])"]
        runAfter:
          - task-switchboard
        taskRef:
          name: task-lint
        workspaces:
          - name: shared-workspace
            workspace: workspace

      - name: ec-task-checks
        when:
          - input: "tasks_pipelines"
            operator: "in"
            values: ["$(tasks.task-switchboard.results.bindings[*])"]
        runAfter:
          - task-switchboard
        taskRef:
          name: ec-checks
        workspaces:
          - name: source
            workspace: workspace

      - name: build-bundles
        when:
          - input: "tasks_pipelines"
            operator: "in"
            values: ["$(tasks.task-switchboard.results.bindings[*])"]
        runAfter:
          - task-switchboard
        params:
          - name: revision
            value: "{{ revision }}"
        workspaces:
          - name: source
            workspace: workspace
        taskSpec:
          params:
            - name: revision
              type: string
          steps:
            - name: build-bundles
              image: $(params.image-target)
              workingDir: $(workspaces.source.path)/source
              script: |
                #!/usr/bin/env bash
                set -e
                git config --global --add safe.directory /workspace/source/source

                QUAY_NAMESPACE=konflux-ci/tekton-catalog \
                BUILD_TAG=$(params.revision) \
                SKIP_BUILD=1 \
                SKIP_PUSH=1 \
                SKIP_INSTALL=1 \
                ./hack/build-and-push.sh
          workspaces:
            - name: source

  taskRunTemplate:
    serviceAccountName: konflux-ci-sa
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
